### ISSUE TITLE
Decide and Update schedule for second day

### ISSUE THREAD

**Issue by amitness** [Code4Nepal/digitalnepal#14]
We need the schedule for the second day of the conference to update in the site [here](https://code4nepal.github.io/digitalnepal/schedule/).

**Comment by ravinepal** [comment]
@studenton  

Here's the tentative schedule. please update the page. 

**
**Note: Here's the tentative agenda. This will likely change as we gather feedback from potential participants about their interest.** 

March 8, 2017 (Venue comigng soon)
1:00 PM-2:00 PM - Welcome and importance of citizen journalism
2:00 PM- 3: PM -  Using smartphone to to take photos and videos, and tell a story. 
3:00- 4:00 PM - Data visualization
4:00 PM- 5:00 PM - Networking, questions and answers. (Food and drinks available.)  


Date: 9th March 2017 ((Venue and speaker details comigng soon)
8 AM - 9AM - Registration and light breakfast. 
9 AM- 9:15- Welcome remarks by the hosts. 
9:15 AM - 9:45 AM - How to use social media responsibly, especially during crisis. 
10:00 AM- 10:30 AM - Inspirational speaker on education, and career. 
10:30 AM-11:15 AM - How can digital tools and platforms be used to tell a powerful story. 
11: 20 AM- 12: 00 PM - Experiences of local youth and changemakers. 
12 PM - 1PM - Lunch Break
1 PM -1:30 -  Speaker on career, and business. 
1:40 PM - 2:50 PM - Soft skills, including public speaking, traiining. 
3:00 PM- 3:30 PM - Leveraging digital technology to build successful companies in Nepal.
3:30 PM- 4:00 PM- TBD.
4:00 PM - 4:30 PM - Panel with guests from outside of Nepal.  
4:30 - 4:45 PM - Tea/snacks break
4:50- 5:30 PM-  Keynote Speaker
5:30PM- 6:30PM - Networking (Food and drinks available.)

**Comment by amitness** [comment]
@ravinepal Done. Have a look and close the issue.

**Comment by ravinepal** [comment]
thanks @studenton
