### ISSUE TITLE
Update location co-ordinate to the venue

### ISSUE THREAD

**Issue by amitness** [Code4Nepal/digitalnepal#15]
Once the exact location for the conference is decided, the map on the homepage needs to be updated with the correct co-ordinates.

**Comment by ShashiAdhikari** [comment]
It is fine for now once the venue will be decide we will put the right co-ordinates.

**Comment by ravinepal** [comment]
i will share this in two weeks once it's confirmed!

**Comment by ravinepal** [comment]
here you go, @studenton : https://www.google.com/search?q=manaki+hotel+janakpur&oq=mana&aqs=chrome.1.69i57j69i59j69i61l2j69i60j0.6290j0j7&sourceid=chrome&ie=UTF-8#q=manaki+hotel+janakpur&rflfq=1&rlha=0&rllag=26723547,85932287,799&tbm=lcl&tbs=lf_msr:-1,lf_pqs:EAE,lf:1,lf_ui:2&rlfi=hd:;si:10222146037878426929;mv:!1m3!1d9465.951824682992!2d85.93228724999994!3d26.723547900000003!3m2!1i860!2i510!4f13.1;tbs:lf_msr:-1,lf_pqs:EAE,lf:1,lf_ui:2

**Comment by ravinepal** [comment]
it's hotel manaki international

**Comment by amitness** [comment]
@ravinepal It's updated. Clicking the icon beside the **Location** text will redirect the user to the map page.
