### ISSUE TITLE
update tweets setting 

### ISSUE THREAD

**Issue by code4nepal** [Code4Nepal/digitalnepal#18]
@studenton -- i think tweets curation setting needs to be updated. i also think we should add #digitaljnk as one more hashtag in addition to #digitalnepal. what do you think?

**Comment by amitness** [comment]
Looked into it. The twitter block is hardcoded for the GDG event only. They've hosted the **mechanism** from which they fetch tweets for **certain hashtag** on their own server. They're using a service called [Tweetledee](http://chrissimpkins.github.io/tweetledee/).

If we want to use twitter content block, we have to set up our own Tweetledee instance.These are the requirements for Tweetledee.

```
Requirements
You will need the following to use Tweetledee:

Access to a web server with PHP version 5.3 or greater. As of Tweetledee v0.4.1, JSON pretty printing is also supported for PHP version 5.3 or greater (previously v5.4+).
libcurl installed on your web server (cURL)
Twitter application OAuth settings and access tokens
Local file write access on the web server (if you are using the caching Tweetledee files)
```

**Comment by amitness** [comment]
@prashishh Need your input on this.

**Comment by code4nepal** [comment]
thanks, @studenton. if it's too time consuming, we can take out twitter section.

**Comment by amitness** [comment]
Yes, it's time consuming and requires server space. I'll take out that section.
