### ISSUE TITLE
update co-organizer section

### ISSUE THREAD

**Issue by code4nepal** [Code4Nepal/digitalnepal#20]
pls replace eejot.org logo with the logo of www.wdac.org.np. here's their image: http://www.wdac.org.np/wp-content/uploads/2016/03/wdac-logo-1.png (also hyperlink the image.)

**Comment by code4nepal** [comment]
@studenton -- sorry shashi seems to be away from computer for other stuff. amit - would you mind updating this too. thanks so much

**Comment by amitness** [comment]
@924231278564d9de65fb8b30083a8dcae44bbde1 fixes it.
