### ISSUE TITLE
unhide/activate team page

### ISSUE THREAD

**Issue by code4nepal** [Code4Nepal/digitalnepal#21]
rename it "about" 

Under Organizers of the page: 

List yourself, Shashi, Asmita, Roshan, Prashish, and me. here's everyone's headshots: http://codefornepal.org/en/team/ (I think we can just have "Code for Nepal" than individual titles.) 

Also list Alisha Chhetri. She is from WDAC. here's her photo: https://plus.google.com/photos/116105646260933446833/albums/profile/6103457784469946018 

And pls list Nanda Kishor Mandal.He is from WDAC. here's his photo: https://www.facebook.com/photo.php?fbid=839611989468231&set=a.101185349977569.2087.100002583125002&type=3&theater (you can crop the window part of the photo.)

**Comment by amitness** [comment]
@codefornepal Are Alisha Chhetri and Nanda Kishor Mandal under Organizers or under Program Committee?  I've added them to Organizers. Can I delete the Program Committee section then?

**Comment by ravinepal** [comment]
Organizers

**Comment by ravinepal** [comment]
Thanks, @studenton Can you arrange names in alphabetical way so your's,
asmita, Alisha's name are on top :)

none of this would be possible without you and team, pls make these changes
so your names are on the top. Also pls check your Fb message

**Comment by amitness** [comment]
@ravinepal Done.
