### ISSUE TITLE
upload speakers photos 

### ISSUE THREAD

**Issue by code4nepal** [Code4Nepal/digitalnepal#23]
[Pls resize all pics to 140x140, and optimize] 

Speaker 1: Anusha Yadav

Photo: 
![image](https://cloud.githubusercontent.com/assets/6979290/22188751/fde09276-e0e5-11e6-9b66-cf6fc6df1207.png)

Affiliation: Accountability Lab

Speaker 2: Yogina Shakya 

Photo: 
![14434916_1211527358869916_7843004118143757102_o](https://cloud.githubusercontent.com/assets/6979290/22394188/06b99ba4-e4e7-11e6-8b81-b87affce39b3.jpg)

Affiliation: Cloud Factory

Speaker 3: Biswas Dhakal 

Photo: 
![biswas](https://cloud.githubusercontent.com/assets/6979290/22188539/466f4520-e0e4-11e6-9143-18c99a961896.jpeg)

Affiliation: F1Soft

Speaker 4: Dietrich Ayala

Photo: https://www.dropbox.com/s/f630wkejjqukwis/dietrich.jpg?dl=0

Affiliation: Mozilla 

Speaker 5: David Carpara 

Photo: ![david1-282x300](https://cloud.githubusercontent.com/assets/6979290/22188637/31f309e6-e0e5-11e6-8f73-bf44e70fa2d9.jpg)

Affiliation: Journalist 

Speaker 6: Promisha Mishra

Photo: ![16237462_1329088623778638_2078490727_n](https://cloud.githubusercontent.com/assets/6979290/22394265/3638d0be-e4e9-11e6-976c-0ef73a8fbe7a.jpg)

Affiliation: Computer Engineer

(Thank you in advance for updating the site, @studenton! Pls let me know if you have qs.)

**Comment by amitness** [comment]
Added the speakers. Getting a issue in building the page.

```
Your site is having problems building: unable to build page. Please try again later.
```

Looking into how to solve it.

**Comment by amitness** [comment]
Fixed the github pages build issue. It's up and running now.

**Comment by amitness** [comment]
@ravinepal Completed. Please review and close the issue.

**Comment by ravinepal** [comment]
thanks, @studenton! We will likely have more speakers and their bios etc later.
