### ISSUE TITLE
update "media partners" to general partners and add this

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/digitalnepal#25]
Madhesi Youth 
![madhesi youth logo_transparent](https://cloud.githubusercontent.com/assets/3759081/22493524/b21759f4-e7fe-11e6-85e6-630591735476.png)

Janakpur Youth Network - JYN 

(This doesn't have logo yet - so instead of coming soon can you just have text that says "Janakpur Youth Network - JYN"

**Comment by amitness** [comment]
Done @ravinepal. Please review and close the issue.

**Comment by ravinepal** [comment]
Thanks, @studenton! One more under general partners: 

![ayon logo](https://cloud.githubusercontent.com/assets/3759081/22535698/b471a52a-e8ca-11e6-943f-55e34fcf272a.jpeg)
