### ISSUE TITLE
update schedule

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/digitalnepal#31]
amit - pls see your email for an updated google doc

**Comment by amitness** [comment]
Done @ravinepal . Please review it [here](http://digitalnepal.org/schedule/).

**Comment by ravinepal** [comment]
thanks! pls add Priyasha Maharjan to the session "Panel from youths in JNK" 

can you rename "Panel from youths in JNK" to "Experiences of young changemakers" 

thanks!

**Comment by amitness** [comment]
@ravinepal Updated. Have a look.
