### ISSUE TITLE
add mozilla as a general sponsor

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/digitalnepal#33]
![image](https://cloud.githubusercontent.com/assets/3759081/23163729/aba56ed6-f801-11e6-8b53-53a3f025f77e.png)

**Comment by amitness** [comment]
@ravinepal Mozilla recently rebranded themselves with a new logo. Do they prefer what you've sent or the new logo? Please confirm.

![](http://1u88jj3r4db2x4txp44yqfj1.wpengine.netdna-cdn.com/wp-content/uploads/2017/01/mozilla_logos.jpg)

**Comment by ravinepal** [comment]
Pls use the new logo. thanks.
