### ISSUE TITLE
Change menu and text on homepage to c4n red

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/digitalnepal#4]
here are the color code: 

 Red: #E00015
Blue: #00ADEF 

so the text is more visible.

**Comment by amitness** [comment]
Haha, three of us had the same thought. Was doing exactly this.

**Comment by ravinepal** [comment]
haha. bro -  we gotta brighten up that photo on the homepage -- right now it looks like a storm is coming -- and it's sad

**Comment by amitness** [comment]
Did that.

**Comment by ravinepal** [comment]
thanks! may be a bit more - and make falgun/march date bold? (sorry i was not able to find good photos for the homepage.)

**Comment by ravinepal** [comment]
amit - where did you get this photo from? i just want to see if it's creative commons or if we need to get permission/buy etc

**Comment by amitness** [comment]
I found it here: http://www.bgfotography.com/wp-content/uploads/2014/11/JanakiTemple.jpg

**Comment by ravinepal** [comment]
thanks. i'm gonna ask the photographer for permission. in the meantime is there a way to give credit to the photographer in the footer, saying this: Photo: Bishal Gautam. 

Also, pls take out shadow from the text on the homepage - -just make bold and brighter?

**Comment by amitness** [comment]
Have a look. Is the text ok?

**Comment by amitness** [comment]
Personally, I liked the default background image better. It fitted better with the white text. Currently, the text doesn't seem upto the mark. It's not so clear.
