### ISSUE TITLE
brighten janaki mandir photo on the homepage and make the menu red/blue

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/digitalnepal#6]
the photo is too dark at the moment -- makes everything look really sad :( 

 Red: #E00015
Blue: #00ADEF

**Comment by amitness** [comment]
I think the menu color is OK as white. Close the issue if you think it's fine.

**Comment by ShashiAdhikari** [comment]
I think it' good. What do you say ravi?

**Comment by ravinepal** [comment]
thanks @studenton and @ShashiAdhikari
