### ISSUE TITLE
Delete pricetable section from the homepage

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/digitalnepal#8]
pls delete pricetable section

Pricetable

-5%
Early Bird
350 UAH
Lorem ipsum is simply
Dummy text of the printing
Typesetting industry
Buy Now
-20%
Last Chance

450 UAH
Lorem ipsum is simply
Dummy text of the printing
Typesetting industry
Ticket sales will begin on 1 October 2014 00:00
Student
200 UAH
Lorem ipsum is simply
Dummy text of the printing
Typesetting industry
Sold Out

**Comment by ShashiAdhikari** [comment]
done!
